summarize/__init__.py
from flask import Flask
from .routes import main
from .sockets import socketio


def create_app():
    """
    Create and configure the Flask app.

    Returns:
        Flask: The configured Flask app.
    """
    app = Flask(__name__)

    # Set configuration options for the Flask app
    app.config['DEBUG'] = True
    app.config['SECRET_KEY'] = 'thisIsASecretKey'

    with app.app_context():
        # Register the main blueprint containing your routes
        app.register_blueprint(main)

        # Initialize Socket.IO with the Flask app
        socketio.init_app(app)

    return app

summarize/routes.py
"""This module contains the accessible routes by the flask application"""

import os
import shutil
from flask import render_template, redirect, request, Blueprint, url_for, current_app, send_file, jsonify
from .functions import allowed_file, gen_audio
from werkzeug.utils import secure_filename

main = Blueprint("main", __name__)

UPLOAD_FOLDER = 'uploads'

pdf_path = {
    'path': ''
}

download_path = {
    'path': '',
    'file_name': '',
    'audio_path': ''
}


@main.route('/')
def home():
    """Render the home page."""
    return render_template('home.html')


@main.route('/create', methods=['GET', 'POST'])
def create():
    """Render the create page and handle file upload and redirect to the summarization page."""
    if request.method == 'POST':
        current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
        if not request.files:
            return redirect(request.url)
        print(request.files['file'])
        file = request.files['file']
        if file.filename == '':
            return redirect(request.url)

        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            file.save(file_path)
            pdf_path['path'] = file_path
            spl = file_path.split('\\')
            file_name = spl[-1][:-4]
            download_path['file_name'] = f"{file_name}"
            download_path['path'] = f"uploads/{file_name}_summary.txt"
            return redirect(url_for('main.summarize'))

    return render_template("create.html", layout='create')


@main.route('/summarize')
def summarize():
    """Render the summarization page."""
    return render_template('summarize_page.html')


@main.route('/summ_download', methods=['POST', 'GET'])
def download():
    """Download the summary file."""
    full_path = os.path.abspath(download_path['path'])
    return send_file(full_path,
                     download_name=f"{download_path['file_name']}_summary.txt",
                     as_attachment=True)


@main.route('/audio')
def audio():
    """Render the audio generation page."""
    return render_template('create.html', layout='audio')


@main.route('/audio_gen')
def audio_gen():
    """Generate audio from the summary and return a JSON response."""
    file_name = download_path['file_name']
    with open(download_path['path']) as txt:
        text = txt.read()

    gen_audio(file_name, text)

    file_path = f"uploads/{file_name}_audioBook.mp3"
    download_path['audio_path'] = file_path

    response_data = {
        'status': 'success',
        'message': 'Audio file generated successfully',
        'file_path': file_path
    }

    return jsonify(response_data)


@main.route('/audio_download')
def audio_download():
    """Download the generated audio file."""
    full_path = os.path.abspath(download_path['audio_path'])
    return send_file(full_path,
                     download_name=f"{download_path['file_name']}_audiobook.mp3",
                     as_attachment=True)


@main.route('/admin')
def admin():
    """Admin route used for clearing the contents of the 'uploads' folder."""
    folder_path = 'uploads'
    shutil.rmtree(folder_path, ignore_errors=True)
    os.makedirs(folder_path, exist_ok=True)
    return redirect(url_for('main.home'))

summarize/templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-100" data-bs-theme="auto">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">
    <title>Open Blinkist</title>

    {% block header %}

    {% endblock %}

  </head>
  <body>
  <div class="cover-container d-flex w-100 h-100 p-1 mx-auto flex-column">
  <nav class="navbar navbar-expand-lg bg-body-light px-lg-5 px-sm-0">
    <div class="container-fluid">
      <a class="navbar-brand" id="nav_brand" href="{{ url_for('main.home') }}" style="font-size: 24px; pointer-events:auto;">Open Blinkist</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">

        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" id="homeNavItem" href="{{ url_for('main.home') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="createNavItem" href="{{ url_for('main.create') }}">Create</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="aboutNavItem" href="{{ url_for('main.home') }}">About</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}

  {% endblock %}

  </div>
  </body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</html>

summarize/templates/create.html
{% extends 'base.html' %}

{% block header %}
  <link href="{{ url_for('static', filename='css/create.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock %}

{% block content %}
<hr/>
{% if layout == 'create' %}

<div class="create">
  <div class="col-lg-4 mx-auto" style="width: 350px;">
    <div class="p-3 bg-white shadow rounded-lg" style="height: 320px;">
      <img src="https://res.cloudinary.com/mhmd/image/upload/v1557366994/img_epm3iz.png" alt="" width="100" class="d-block mx-auto mb-4 mt-4">
      <form method="POST" enctype="multipart/form-data">
        <div class="py-4">
          <input class="form-control form-control-sm rounded-pill" id="file" name="file" type="file" />
        </div>
        <div class="py-3">
          <label for="fileUpload" class="file-upload btn btn-primary btn-block rounded-pill shadow">Upload
            <input id="fileUpload" type="submit" hidden>
          </label>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="infoPanel">
  <p>
    Note: Before summarizing, some things to keep in mind<br/>
    <br/>
    > The project is still under development, so the results may be unsatisfactory.<br/>
    > Only pdfs are allowed<br/>
    > Summarizing long text takes a lot of time, so preferably use this to summarize short pdfs.<br/>
    (Although you can use this to summarize long pdfs, it may take a while
  </p>
</div>

{% elif layout == 'audio' %}

<div class="audio_file">
  <p class="mb-0">Click to generate audio.</p>
  <button type="button" class="btn btn-outline-primary" id="generateAudio">Generate Audio</button>
  <button type="button" class="btn btn-outline-secondary" disabled id="downloadAudio">Download Audio</button>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
    var generateButton = document.getElementById('generateAudio');
    var downloadButton = document.getElementById('downloadAudio');

    generateButton.addEventListener('click', function() {
        // Generate audio logic here
        generateButton.setAttribute('disabled', true);
        downloadButton.setAttribute('disabled', true);

        var xhr = new XMLHttpRequest();
        xhr.open('GET', '/audio_gen', true);

        xhr.onload = function() {
            if (xhr.status === 200) {
                console.log(xhr.responseText);
                downloadButton.removeAttribute('disabled');
                // You can trigger additional actions here based on the response
            } else {
                console.error('Error:', xhr.status);
            }
        };

        xhr.send();
    });

    downloadButton.addEventListener('click', function() {
        window.location.href = '{{ url_for('main.audio_download') }}';
    });
});
</script>
{% endif %}

{% endblock %}

summarize/templates/home.html
{% extends 'base.html' %}

{% block header %}
  <link href="{{ url_for('static', filename='css/home.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}

<body class="h-100 text-center text-bg-dark">
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <main class="center-content">
      <h1>Summarize and Listen</h1>
      <p class="lead">Transform books into concise audiobooks. Simplify reading, save time. Try now for efficient learning or leisure on-the-go.</p>
      <p class="lead">
        <a href="{{ url_for('main.create') }}" class="btn btn-lg btn-outline-light ">Get started</a>
      </p>
    </main>
    <footer class="mt-auto pb-2 text-white-50">
      <a href="" target="_blank">
        <img src="{{ url_for('static', filename='img/Github.png') }}" alt="Github" width="25" height="25" style="-webkit-filter: invert(1); filter: invert(1);">
      </a>
    </footer>
  </div>
</body>

{% endblock %}

summarize/templates/summarize_page.html
{% extends 'base.html' %}

{% block header %}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/summary_page.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}

<body>
  <hr/>
  <div class="messages">

    <div class='container cont1'>
      <div class="header">
        <h4>Backend Processes will be displayed here.</h4>
      </div>
      <div class="scrollable-container">
        <div class="scrollable-content" id="statusMessage">
          <!--The Backend messages will be displayed here-->

        </div>
      </div>
    </div>

    <div class='container cont2'>
      <div class="header">
        <h4>The summary will be displayed here.</h4>
      </div>
      <div class="scrollable-container">
        <div class="scrollable-content" id="summaryResult">
          Your Summary is being generated.
        </div>
      </div>
    </div>

  </div>

  <div class="buttons gap-2 justify-content-center py-5">
    <button type="button" class="btn btn-outline-primary" onclick="window.location.href='{{ url_for('main.audio') }}'" disabled>Generate Audio</button>
    <button type="button" class="btn btn-outline-secondary" href="{{ url_for('main.download') }}" disabled>Download summary</button>
    <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#infoModal">Info</button>
  </div>

  <div class="modal fade" id="infoModal" tabindex="-1" aria-labelledby="infoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="infoModalLabel">How this works...</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          The webpage provides real-time updates on the backend processes: <br/>
          <br/>
          1. **Preprocess and Chunking**: These initial steps are performed swiftly, and the system promptly displays the number of resulting chunks. <br/>
          <br/>
          2. **Summarization Process**: The model then comprehensively summarizes each chunk. Depending on the model chosen—'bart-base' or 'bart-large-cnn'—the summarization time varies. 'bart-base' averages around 10 seconds per chunk, producing somewhat illegible summaries, while 'bart-large-cnn' takes approximately 30 seconds or a bit more but yields better results with occasional irregularities. <br/>
          <br/>
          3. **Displaying Results**: After summarizing each chunk, the summary text is presented in a designated text-box.<br/>
          <br/>
          4. **Button States**: Throughout the backend process, all buttons are intentionally disabled to ensure a smooth workflow and prevent potential issues. These buttons become active once the summarization process is successfully completed. <br/>
          <br/>
          5. **Download Options**: Users are provided with the flexibility to download the generated summary text file or convert it into an audio file. <br/>
          <br/>
          Please note that the choice of model impacts both the summarization time and the quality of the generated summaries. The system prioritizes user experience by keeping buttons disabled during the backend processes and enabling them once the summarization is finished.<br/>
        </div>
      </div>
    </div>
  </div>

</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

<script type="text/javascript" charset="utf-8">
  var socket = io.connect();

  var audioButton = document.querySelector('.btn-outline-primary');
  var downloadButton = document.querySelector('.btn-outline-secondary');
  var logo = document.getElementById('nav_brand');
  var homeNavItem = document.getElementById('homeNavItem');
  var createNavItem = document.getElementById('createNavItem');
  var aboutNavItem = document.getElementById('aboutNavItem');

  socket.on('connect', function() {
      console.log('connected');
      logo.style.pointerEvents = 'none';
      homeNavItem.classList.add('disabled');
      createNavItem.classList.add('disabled');
      aboutNavItem.classList.add('disabled');
  });

  socket.on('status', function(text) {
      console.log('received');
      var text = text['text'];
      document.getElementById("statusMessage").innerHTML += text + "<br>";
      socket.emit('preprocess', {'text': 'Chunking'});
  });

  socket.on('pr-status', function(text) {
  console.log(text['num']);
      if (text['num'] == 2) {
          console.log('chunking');
          var text = text['text'];
          document.getElementById("statusMessage").innerHTML += text + "<br>";
          socket.emit('chunk', {'text': 'begin chunking'});
      } else {
          console.log('Preprocess Complete');
          var text = text['text'];
          document.getElementById("statusMessage").innerHTML += text + "<br>";
      }
  });

  socket.on('chunking', function(text) {
      if (text['num'] == 2) {
          console.log('Chunking Complete');
          var text = text['text'];
          document.getElementById("statusMessage").innerHTML += text + "<br>";
      } else {
          var text = text['text'];
          document.getElementById("statusMessage").innerHTML += text + "<br>";
          socket.emit('chunk_summarize', {'text': 'Summarizing each chunk'});
      }
  });

  socket.on('summ_chunk', function(text) {
      if (text['num'] == 2) {
          console.log('Summarizing Chunk' + text['count']);
          var text = text['text'];
          document.getElementById("statusMessage").innerHTML += text + "<br>";
      } else {
          console.log('Summarizing Chunks');
          var text = text['text'];
          document.getElementById("statusMessage").innerHTML += text + "<br>";
      }
  });

  socket.on('chunk_done', function(text) {
      console.log('Chunks Summarized');
      var text = text['text'];
      document.getElementById("statusMessage").innerHTML += text + "<br>";
      socket.emit('post_process', {'text': 'Starting Post-Process'});
  });

  socket.on('end_phase', function(text) {
      if (text['num'] == 1) {
          console.log('Postprocessing summary');
          var text = text['text'];
          document.getElementById("statusMessage").innerHTML += text + "<br>";
      } else if (text['num'] == 2) {
          console.log('Calculating Scores');
          var text = text['text'];
          document.getElementById("statusMessage").innerHTML += text + "<br>";
      } else {
          console.log('Scores of the summary');
          var text = text['text'];
          document.getElementById("statusMessage").innerHTML += text + "<br>";
      }
  });

  socket.on('summary', function(text) {
      console.log("Summary complete");
      var summary = text['text'];
      document.getElementById("summaryResult").innerHTML = "<br><br>"+ summary + "<br>";

      logo.style.pointerEvents = 'auto';
      homeNavItem.classList.remove('disabled');
      createNavItem.classList.remove('disabled');
      aboutNavItem.classList.remove('disabled');
      downloadButton.removeAttribute('disabled');
      audioButton.removeAttribute('disabled');
  });

  downloadButton.addEventListener('click', function() {
        window.location.href = '{{ url_for('main.download') }}';
  });

</script>

{% endblock %}